name: 'Continue Integration'

on:
  push:
    paths-ignore:
      - output/**

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm ci
      - run: node ./src/index.js
      - name: Commit changes
        run: |
          git config --global user.email "dominikszamburski99@gmail.com"
          git config --global user.name "Dominik Szamburski"
          git add output/
          git commit -m "Update resume"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}